const config = {
  source: ['tokens/**/*.json'],
  hooks: {
    transforms: {
      'name/path': {
        type: 'name',
        transform: (token) => token.path.join('-'),
      },
      'duration/css': {
        type: 'value',
        filter: (token) => token.$type === 'duration',
        transform: (token) => `${token.$value.value}${token.$value.unit}`,
      },
    },
    fileHeaders: {
      generated: () => [
        'Generated by Style Dictionary from tokens/. Do not edit by hand.',
        'Change the tokens, then run `npm run tokens`.',
      ],
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['name/path', 'duration/css'],
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            fileHeader: 'generated',
          },
        },
      ],
    },
  },
};

export default config;
